apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: sdu5lona9-python 
  janus-idp.io/tekton: sdu5lona9-python
  backstage.io/kubernetes-id: sdu5lona9-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sdu5lona9-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml